### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ArturFormella** [jquesnelle/transformers-openai-api#6]
```
(.venv) (base) ➜  source .venv/bin/activate
(.venv) (base) ➜  git clone https://github.com/jquesnelle/transformers-openai-api
(.venv) (base) ➜  cd transformers-openai-api
(.venv) (base) ➜  cp config.example.json config.json
(.venv) (base) ➜  pip install -r requirements.txt
(.venv) (base) ➜  python transformers_openai_api/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/T8/transformers-openai-api/transformers-openai-api/./transformers_openai_api/__main__.py", line 4, in <module>
    from .app import make_transformers_openai_api
ImportError: attempted relative import with no known parent package

```

**Comment by asvdvl** [comment]
This command from the main directory worked for me:
```
python -m transformers_openai_api
```
